/*
 * Created on 2017-02-28 ( Date ISO 2017-02-28 - Time 11:52:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import java.util.List;

import org.demo.data.record.EleveRecord;

/**
 * Persistence Interface for EleveRecord.
 */
public interface ElevePersistence { 

	/**
	 * Tries to find an entity using its Id / Primary Key
	 * @param idEleve
	 * @return entity
	 */
	EleveRecord findById( Integer idEleve  ) ;

	/**
	 * Finds all entities.
	 * @return all entities
	 */
	List<EleveRecord> findAll();

	/**
	 * Counts all the records present in the database
	 * @return
	 */
	public long countAll() ;


	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	EleveRecord save(EleveRecord entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return true if the entity has been updated, false if not found and not updated
	 */
	boolean update(EleveRecord entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	EleveRecord create(EleveRecord entity);

	/**
	 * Deletes an entity using its Id / Primary Key
	 * @param idEleve
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean deleteById( Integer idEleve );

	/**
	 * Deletes an entity using the Id / Primary Key stored in the given object
	 * @param the entity to be deleted (supposed to have a valid Id/PK )
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean delete( EleveRecord entity );

	/**
	 * Returns true if an entity exists with the given Id / Primary Key 
	 * @param idEleve
	 * @return
	 */
	public boolean exists( Integer idEleve ) ;

	/**
	 * Returns true if the given entity exists
	 * @param entity
	 * @return
	 */
	public boolean exists( EleveRecord entity ) ;

}
