/*
 * Created on 2017-02-28 ( Date ISO 2017-02-28 - Time 11:53:00 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import java.util.List;

import org.demo.data.record.NoteRecord;

/**
 * Persistence Interface for NoteRecord.
 */
public interface NotePersistence { 

	/**
	 * Tries to find an entity using its Id / Primary Key
	 * @return entity
	 */
	NoteRecord findById(   ) ;

	/**
	 * Finds all entities.
	 * @return all entities
	 */
	List<NoteRecord> findAll();

	/**
	 * Counts all the records present in the database
	 * @return
	 */
	public long countAll() ;


	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	NoteRecord save(NoteRecord entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return true if the entity has been updated, false if not found and not updated
	 */
	boolean update(NoteRecord entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	NoteRecord create(NoteRecord entity);

	/**
	 * Deletes an entity using its Id / Primary Key
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean deleteById(  );

	/**
	 * Deletes an entity using the Id / Primary Key stored in the given object
	 * @param the entity to be deleted (supposed to have a valid Id/PK )
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean delete( NoteRecord entity );

	/**
	 * Returns true if an entity exists with the given Id / Primary Key 
	 * @return
	 */
	public boolean exists(  ) ;

	/**
	 * Returns true if the given entity exists
	 * @param entity
	 * @return
	 */
	public boolean exists( NoteRecord entity ) ;

}
