/*
 * Created on 2017-03-08 ( Date ISO 2017-03-08 - Time 14:26:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import java.util.List;

import org.demo.data.record.TypementionRecord;

/**
 * Persistence Interface for TypementionRecord.
 */
public interface TypementionPersistence { 

	/**
	 * Tries to find an entity using its Id / Primary Key
	 * @param idMention
	 * @return entity
	 */
	TypementionRecord findById( Integer idMention  ) ;

	/**
	 * Finds all entities.
	 * @return all entities
	 */
	List<TypementionRecord> findAll();

	/**
	 * Counts all the records present in the database
	 * @return
	 */
	public long countAll() ;


	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TypementionRecord save(TypementionRecord entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return true if the entity has been updated, false if not found and not updated
	 */
	boolean update(TypementionRecord entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TypementionRecord create(TypementionRecord entity);

	/**
	 * Deletes an entity using its Id / Primary Key
	 * @param idMention
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean deleteById( Integer idMention );

	/**
	 * Deletes an entity using the Id / Primary Key stored in the given object
	 * @param the entity to be deleted (supposed to have a valid Id/PK )
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean delete( TypementionRecord entity );

	/**
	 * Returns true if an entity exists with the given Id / Primary Key 
	 * @param idMention
	 * @return
	 */
	public boolean exists( Integer idMention ) ;

	/**
	 * Returns true if the given entity exists
	 * @param entity
	 * @return
	 */
	public boolean exists( TypementionRecord entity ) ;

}
