/*
 * Created on 2017-03-08 ( Date ISO 2017-03-08 - Time 14:26:33 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence;

import java.util.List;

import org.demo.data.record.TypesexeRecord;

/**
 * Persistence Interface for TypesexeRecord.
 */
public interface TypesexePersistence { 

	/**
	 * Tries to find an entity using its Id / Primary Key
	 * @param idSexe
	 * @return entity
	 */
	TypesexeRecord findById( Integer idSexe  ) ;

	/**
	 * Finds all entities.
	 * @return all entities
	 */
	List<TypesexeRecord> findAll();

	/**
	 * Counts all the records present in the database
	 * @return
	 */
	public long countAll() ;


	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TypesexeRecord save(TypesexeRecord entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return true if the entity has been updated, false if not found and not updated
	 */
	boolean update(TypesexeRecord entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TypesexeRecord create(TypesexeRecord entity);

	/**
	 * Deletes an entity using its Id / Primary Key
	 * @param idSexe
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean deleteById( Integer idSexe );

	/**
	 * Deletes an entity using the Id / Primary Key stored in the given object
	 * @param the entity to be deleted (supposed to have a valid Id/PK )
	 * @return true if the entity has been deleted, false if not found and not deleted
	 */
	boolean delete( TypesexeRecord entity );

	/**
	 * Returns true if an entity exists with the given Id / Primary Key 
	 * @param idSexe
	 * @return
	 */
	public boolean exists( Integer idSexe ) ;

	/**
	 * Returns true if the given entity exists
	 * @param entity
	 * @return
	 */
	public boolean exists( TypesexeRecord entity ) ;

}
