/*
 * Created on 2017-03-08 ( Date ISO 2017-03-08 - Time 14:27:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.impl.jdbc;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import javax.inject.Named;


import org.demo.data.record.TypementionRecord ;
import org.demo.persistence.TypementionPersistence;
import org.demo.persistence.impl.jdbc.commons.GenericDAO;

/**
 * Typemention persistence implementation 
 * 
 * @author Telosys
 *
 */
@Named("TypementionPersistence")
public class TypementionPersistenceJdbc extends GenericDAO<TypementionRecord> implements TypementionPersistence {

	private final static String SQL_SELECT_ALL = 
		"select ID_MENTION, LABEL_MENTION from typemention"; 

	private final static String SQL_SELECT = 
		"select ID_MENTION, LABEL_MENTION from typemention where ID_MENTION = ?";

	private final static String SQL_INSERT = 
		"insert into typemention ( ID_MENTION, LABEL_MENTION ) values ( ?, ? )";

	private final static String SQL_UPDATE = 
		"update typemention set LABEL_MENTION = ? where ID_MENTION = ?";

	private final static String SQL_DELETE = 
		"delete from typemention where ID_MENTION = ?";

	private final static String SQL_COUNT_ALL = 
		"select count(*) from typemention";

	private final static String SQL_COUNT = 
		"select count(*) from typemention where ID_MENTION = ?";

    //----------------------------------------------------------------------
	/**
	 * DAO constructor
	 */
	public TypementionPersistenceJdbc() {
		super();
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForPrimaryKey(PreparedStatement ps, int i, TypementionRecord typemention) throws SQLException {
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, typemention.getIdMention() ) ; // "ID_MENTION" : java.lang.Integer
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForInsert(PreparedStatement ps, int i, TypementionRecord typemention) throws SQLException {
		//--- Set PRIMARY KEY and DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, typemention.getIdMention() ) ; // "ID_MENTION" : java.lang.Integer
		setValue(ps, i++, typemention.getLabelMention() ) ; // "LABEL_MENTION" : java.lang.String
	}

    //----------------------------------------------------------------------
	@Override
	protected void setValuesForUpdate(PreparedStatement ps, int i, TypementionRecord typemention) throws SQLException {
		//--- Set DATA from bean to PreparedStatement ( SQL "SET x=?, y=?, ..." )
		setValue(ps, i++, typemention.getLabelMention() ) ; // "LABEL_MENTION" : java.lang.String
		//--- Set PRIMARY KEY from bean to PreparedStatement ( SQL "WHERE key=?, ..." )
		setValue(ps, i++, typemention.getIdMention() ) ; // "ID_MENTION" : java.lang.Integer
	}

	//----------------------------------------------------------------------
	/**
	 * Creates a new instance of the bean and populates it with the given primary value(s)
	 * @param idMention;
	 * @return the new instance
	 */
	private TypementionRecord newInstanceWithPrimaryKey( Integer idMention ) {
		TypementionRecord typemention = new TypementionRecord();
		typemention.setIdMention( idMention );
		return typemention ;
	}

	//----------------------------------------------------------------------
	@Override
	protected TypementionRecord newInstance() {
		return new TypementionRecord() ;
	}

    //----------------------------------------------------------------------
	@Override
	protected TypementionRecord populateBean(ResultSet rs, TypementionRecord typemention) throws SQLException {

		//--- Set data from ResultSet to Bean attributes
		typemention.setIdMention(rs.getInt("ID_MENTION")); // java.lang.Integer
		if ( rs.wasNull() ) { typemention.setIdMention(null); }; // not primitive number => keep null value if any
		typemention.setLabelMention(rs.getString("LABEL_MENTION")); // java.lang.String
		return typemention ;
	}

	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public TypementionRecord findById( Integer idMention ) {
		TypementionRecord typemention = newInstanceWithPrimaryKey( idMention ) ;
		if ( super.doSelect(typemention) ) {
			return typemention ;
		}
		else {
			return null ; // Not found
		}
	}
	//----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public List<TypementionRecord> findAll() {
		return super.doSelectAll();
	}

	//----------------------------------------------------------------------
	/**
	 * Loads the given bean, it is supposed to contains the primary key value(s) in its attribute(s)<br>
	 * If found, the given instance is populated with the values retrieved from the database<br>
	 * If not found, the given instance remains unchanged
	 * @param typemention
	 * @return true if found, false if not found
	 */
	//@Override
	public boolean load( TypementionRecord typemention ) {
		return super.doSelect(typemention) ;
	}

    //----------------------------------------------------------------------
	/**
	 * Inserts the given bean in the database 
	 * @param typemention
	 */
	public long insert(TypementionRecord typemention) {
		super.doInsert(typemention);
		return 0L ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public TypementionRecord create(TypementionRecord typemention) {
		insert(typemention);
		return typemention ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean update(TypementionRecord typemention) {
		int r = super.doUpdate(typemention);
		return r > 0 ;

	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public TypementionRecord save(TypementionRecord typemention) {
		if ( super.doExists(typemention) ) {
			super.doUpdate(typemention);
		}
		else {
			super.doInsert(typemention);
		}
		return typemention ;
	}	

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean deleteById( Integer idMention ) {
		TypementionRecord typemention = newInstanceWithPrimaryKey( idMention ) ;
		int r = super.doDelete(typemention);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see interface 
	 */
	@Override
	public boolean delete( TypementionRecord typemention ) {
		int r = super.doDelete(typemention);
		return r > 0 ;
	}

    //----------------------------------------------------------------------
	/**
	 * Checks the existence of a record in the database using the given primary key value(s)
	 * @param idMention;
	 * @return
	 */
	// @Override
	public boolean exists( Integer idMention ) {
		TypementionRecord typemention = newInstanceWithPrimaryKey( idMention ) ;
		return super.doExists(typemention);
	}
    //----------------------------------------------------------------------
	/**
	 * Checks the existence of the given bean in the database 
	 * @param typemention
	 * @return
	 */
	// @Override
	public boolean exists( TypementionRecord typemention ) {
		return super.doExists(typemention);
	}

    //----------------------------------------------------------------------
	/**
	 * Counts all the records present in the database
	 * @return
	 */
	@Override
	public long countAll() {
		return super.doCountAll();
	}

    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelect() {
		return SQL_SELECT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlSelectAll() {
		return SQL_SELECT_ALL;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlInsert() {
		return SQL_INSERT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlUpdate() {
		return SQL_UPDATE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlDelete() {
		return SQL_DELETE ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCount() {
		return SQL_COUNT ;
	}
    //----------------------------------------------------------------------
	@Override
	protected String getSqlCountAll() {
		return SQL_COUNT_ALL ;
	}

}
