/*
 * Created on 2017-02-28 ( Date ISO 2017-02-28 - Time 17:44:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.Hashtable;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import javax.inject.Named;


import org.demo.data.record.EleveRecord;
import org.demo.persistence.ElevePersistence;

@Named("ElevePersistence")
public class ElevePersistenceImplFake implements ElevePersistence {

	private final static Map<String,EleveRecord> map = new Hashtable<String,EleveRecord>() ;

	private void checkNotNull(Object o) {
		if ( o == null ) {
			throw new IllegalArgumentException("Key element is null");
		}
	}

	/**
	 * Build the String key from this entity
     * @param idEleve 
	 * @return the key
	 */
	private final String getKey( Integer idEleve ) {
		checkNotNull(idEleve);
		return ""  + idEleve + "|"  ;
	}

	@Override
	public EleveRecord findById(Integer idEleve) {
		String key = getKey( idEleve );
		return map.get(key);
	}

	@Override
	public List<EleveRecord> findAll() {
		List<EleveRecord> list = new LinkedList<EleveRecord>();
		for ( EleveRecord entity : map.values() ) {
			list.add(entity);
		}
		return list;
	}

	@Override
	public long countAll() {
		return map.size() ;
	}

	@Override
	public EleveRecord save(EleveRecord entity) {
		String key = getKey( entity.getIdEleve() );
		map.put(key, entity );
		return entity;
	}

	@Override
	public boolean update(EleveRecord entity) {
		String key = getKey( entity.getIdEleve() );
		if ( map.get(key) == null ) {
			// Doesn't Exist => no update
			return false ;
		}
		else {
			// Exists => update
			map.put(key, entity );
			return true ;
		}
	}

	@Override
	public EleveRecord create(EleveRecord entity) {
		String key = getKey( entity.getIdEleve() );
		if ( map.get(key) == null ) {
			map.put(key, entity );
			return entity ;
		}
		else {
			throw new RuntimeException("EleveRecord - Duplicate key : " + key );
		}
	}

	@Override
	public boolean deleteById(Integer idEleve) {
		String key = getKey(idEleve);
		EleveRecord deleted = map.remove(key);
		return deleted != null ;
	}

	@Override
	public boolean delete(EleveRecord entity) {
		String key = getKey( entity.getIdEleve() );
		EleveRecord deleted = map.remove(key);
		return deleted != null ;
	}

	@Override
	public boolean exists(Integer idEleve) {
		return findById(idEleve) != null ;
	}

	@Override
	public boolean exists(EleveRecord entity) {
		return findById( entity.getIdEleve() ) != null ;
	}

}
