/*
 * Created on 2017-02-28 ( Date ISO 2017-02-28 - Time 17:44:24 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.persistence.impl.fake;

import java.util.Hashtable;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import javax.inject.Named;


import org.demo.data.record.NoteRecord;
import org.demo.persistence.NotePersistence;

@Named("NotePersistence")
public class NotePersistenceImplFake implements NotePersistence {

	private final static Map<String,NoteRecord> map = new Hashtable<String,NoteRecord>() ;

	private void checkNotNull(Object o) {
		if ( o == null ) {
			throw new IllegalArgumentException("Key element is null");
		}
	}

	/**
	 * Build the String key from this entity
     * @param idCours 
     * @param idEleve 
	 * @return the key
	 */
	private final String getKey( Integer idCours, Integer idEleve ) {
		checkNotNull(idCours);
		checkNotNull(idEleve);
		return ""  + idCours + "|"  + idEleve + "|"  ;
	}

	@Override
	public NoteRecord findById(Integer idCours, Integer idEleve) {
		String key = getKey( idCours, idEleve );
		return map.get(key);
	}

	@Override
	public List<NoteRecord> findAll() {
		List<NoteRecord> list = new LinkedList<NoteRecord>();
		for ( NoteRecord entity : map.values() ) {
			list.add(entity);
		}
		return list;
	}

	@Override
	public long countAll() {
		return map.size() ;
	}

	@Override
	public NoteRecord save(NoteRecord entity) {
		String key = getKey( entity.getIdCours(), entity.getIdEleve() );
		map.put(key, entity );
		return entity;
	}

	@Override
	public boolean update(NoteRecord entity) {
		String key = getKey( entity.getIdCours(), entity.getIdEleve() );
		if ( map.get(key) == null ) {
			// Doesn't Exist => no update
			return false ;
		}
		else {
			// Exists => update
			map.put(key, entity );
			return true ;
		}
	}

	@Override
	public NoteRecord create(NoteRecord entity) {
		String key = getKey( entity.getIdCours(), entity.getIdEleve() );
		if ( map.get(key) == null ) {
			map.put(key, entity );
			return entity ;
		}
		else {
			throw new RuntimeException("NoteRecord - Duplicate key : " + key );
		}
	}

	@Override
	public boolean deleteById(Integer idCours, Integer idEleve) {
		String key = getKey(idCours, idEleve);
		NoteRecord deleted = map.remove(key);
		return deleted != null ;
	}

	@Override
	public boolean delete(NoteRecord entity) {
		String key = getKey( entity.getIdCours(), entity.getIdEleve() );
		NoteRecord deleted = map.remove(key);
		return deleted != null ;
	}

	@Override
	public boolean exists(Integer idCours, Integer idEleve) {
		return findById(idCours, idEleve) != null ;
	}

	@Override
	public boolean exists(NoteRecord entity) {
		return findById( entity.getIdCours(), entity.getIdEleve() ) != null ;
	}

}
