/*
 * Created on 2017-03-08 ( Date ISO 2017-03-08 - Time 14:25:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */
package org.demo.data.record.listitem;

import org.demo.data.record.TypementionRecord;
import org.demo.commons.ListItem;

public class TypementionListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TypementionListItem(TypementionRecord typemention) {
		super();

		this.value = ""
			 + typemention.getIdMention()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = typemention.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
