/*
 * Created on 2017-02-28 ( Date ISO 2017-02-28 - Time 11:53:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */

package org.demo.persistence.commons;

/**
 * The pattern defined here is used by the Persistence Service Provider <br>
 * to build the service implementation class name <br>
 * 
 * @author Telosys
 *
 */
public class PersistenceFakeServicePattern {

	public final static String  PATTERN = "%s.impl.fake.%sImplFake" ;
	
}
