/*
 * Created on 2017-02-28 ( Date ISO 2017-02-28 - Time 17:44:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.data.record;

import java.io.Serializable;
import javax.validation.constraints.*;


/**
 * Java bean for entity "cours" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class CoursRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Integer idCours ; // Integer // Id or Primary Key

    @Size( max = 254 )
    private String libelle ;  // String 

    private Integer nbHeures ;  // Integer 

    /**
     * Default constructor
     */
    public CoursRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idCours" field value
     * This field is mapped on the database column "ID_COURS" ( type "INT", NotNull : true ) 
     * @param idCours
     */
	public void setIdCours( Integer idCours ) {
        this.idCours = idCours ;
    }
    /**
     * Get the "idCours" field value
     * This field is mapped on the database column "ID_COURS" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdCours() {
        return this.idCours;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "libelle" field value
     * This field is mapped on the database column "LIBELLE" ( type "VARCHAR", NotNull : false ) 
     * @param libelle
     */
    public void setLibelle( String libelle ) {
        this.libelle = libelle;
    }
    /**
     * Get the "libelle" field value
     * This field is mapped on the database column "LIBELLE" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getLibelle() {
        return this.libelle;
    }

    /**
     * Set the "nbHeures" field value
     * This field is mapped on the database column "NB_HEURES" ( type "INT", NotNull : false ) 
     * @param nbHeures
     */
    public void setNbHeures( Integer nbHeures ) {
        this.nbHeures = nbHeures;
    }
    /**
     * Get the "nbHeures" field value
     * This field is mapped on the database column "NB_HEURES" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getNbHeures() {
        return this.nbHeures;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idCours);
        sb.append("|");
        sb.append(libelle);
        sb.append("|");
        sb.append(nbHeures);
        return sb.toString(); 
    } 



}
