/*
 * Created on 2017-03-08 ( Date ISO 2017-03-08 - Time 14:25:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.data.record;

import java.io.Serializable;
import javax.validation.constraints.*;


/**
 * Java bean for entity "typesexe" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class TypesexeRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Integer idSexe ; // Integer // Id or Primary Key

    @NotNull
    @Size( min = 1, max = 150 )
    private String labelSexe ;  // String 

    /**
     * Default constructor
     */
    public TypesexeRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idSexe" field value
     * This field is mapped on the database column "ID_SEXE" ( type "INT", NotNull : true ) 
     * @param idSexe
     */
	public void setIdSexe( Integer idSexe ) {
        this.idSexe = idSexe ;
    }
    /**
     * Get the "idSexe" field value
     * This field is mapped on the database column "ID_SEXE" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdSexe() {
        return this.idSexe;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "labelSexe" field value
     * This field is mapped on the database column "LABEL_SEXE" ( type "VARCHAR", NotNull : true ) 
     * @param labelSexe
     */
    public void setLabelSexe( String labelSexe ) {
        this.labelSexe = labelSexe;
    }
    /**
     * Get the "labelSexe" field value
     * This field is mapped on the database column "LABEL_SEXE" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getLabelSexe() {
        return this.labelSexe;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idSexe);
        sb.append("|");
        sb.append(labelSexe);
        return sb.toString(); 
    } 



}
