/*
 * Created on 2017-03-08 ( Date ISO 2017-03-08 - Time 14:25:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.data.record;

import java.io.Serializable;
import javax.validation.constraints.*;


/**
 * Java bean for entity "typemention" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class TypementionRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Integer idMention ; // Integer // Id or Primary Key

    @NotNull
    @Size( min = 1, max = 150 )
    private String labelMention ;  // String 

    /**
     * Default constructor
     */
    public TypementionRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "idMention" field value
     * This field is mapped on the database column "ID_MENTION" ( type "INT", NotNull : true ) 
     * @param idMention
     */
	public void setIdMention( Integer idMention ) {
        this.idMention = idMention ;
    }
    /**
     * Get the "idMention" field value
     * This field is mapped on the database column "ID_MENTION" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getIdMention() {
        return this.idMention;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "labelMention" field value
     * This field is mapped on the database column "LABEL_MENTION" ( type "VARCHAR", NotNull : true ) 
     * @param labelMention
     */
    public void setLabelMention( String labelMention ) {
        this.labelMention = labelMention;
    }
    /**
     * Get the "labelMention" field value
     * This field is mapped on the database column "LABEL_MENTION" ( type "VARCHAR", NotNull : true ) 
     * @return the field value
     */
    public String getLabelMention() {
        return this.labelMention;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idMention);
        sb.append("|");
        sb.append(labelMention);
        return sb.toString(); 
    } 



}
